Fix load more podcast + refactor model podcast
PhongHuynh93/BookMultiplatform pull request #15
Opened 2021-09-25 06:55 UTC by nchungdev

- Don't call loadMore in contructor
- Add calculate next page index

2021-09-25 11:32 UTC, PhongHuynh93 requested changes
Need to convert to MVI model.

2021-09-25 15:01 UTC, nchungdev commented
> Need to convert to MVI model.
https://github.com/PhongHuynh93/BookMultiplatform/pull/15/commits/68e8d1e318708bb29d7287b62dcd5bf55c27365f

2021-09-25 15:06 UTC, PhongHuynh93 commented on androidApp/src/main/java/com/wind/book/android/view/podcast/PodcastsFragment.kt
> +            loadMore(true)
Nếu e đặt loadmore trong đây thì bên ios cũng phải tự gọi. Nếu e đặt trong init() trong viewmodel thì nó tự động gọi. Sao e cần đặt trong đây

2021-09-25 15:15 UTC, nchungdev commented on androidApp/src/main/java/com/wind/book/android/view/podcast/PodcastsFragment.kt
> +            loadMore(true)
nếu mình đặt trong init thì lúc mình provide ViewModel trong module nó sẽ tự đi get data luôn a, mặc dù mình chưa gọi
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/46637152/134776425-e141f3a8-12c3-4dfe-a3e9-0f1b8b51f526.png">

2021-09-26 02:18 UTC, PhongHuynh93 approved these changes

2021-09-26 02:19 UTC, merged